spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
        # show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10  # pageable default 설정
        max-page-size: 2000
#        one-indexed-parameters: true # page 번호 1부터.. 단, page 내부 변수랑 데이터가 안 맞음.
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace